build:
  stage: build
  script:
    - cd presentation/01-package-docker
    - make docker-build

cd:
  stage: deploy
  script:
    - cd presentation/01-package-docker
    - docker login --username json_key -p $DOCKER_PASSWORD cr.yandex
    - make docker-push

ci:
  stage: deploy
  needs:
    - cd
  script:
    - kubectl -n shbr rollout restart deployment/shbr-echo