build:
  stage: build
  script:
    - cd presentation/01-package-docker
    - make docker-build

cd:
  stage: deploy
  script:
    - cd presentation/01-package-docker
    - echo $DOCKER_PASSWORD | docker login --username json_key --password-stdin cr.yandex
    - make docker-push

ci:
  stage: deploy
  needs:
    - cd
  script:
    - kubectl -n shbr rollout restart deployment/shbr-echo