- hosts: "all"
  connection: local
  tasks:
    - name: "shbr-echo : container"
      docker_container:
        name: "shbr-03-run-ansible"
        restart_policy: 'always'
        state: 'started'
        image: 'cr.yandex/crpamim8dasm0u97qtpf/shbr-01-package-docker:latest'
        env:
          LANG: java
        ports:
          - "10000:10000"
