apiVersion: apps/v1
kind: Deployment
metadata:
  name: shbr-echo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 33%
      maxUnavailable: 33%
  selector:
    matchLabels:
      app: shbr-echo
  template:
    metadata:
      labels:
        app: shbr-echo
    spec:
      containers:
        - image: cr.yandex/crp5udmc090nv4rpkk6c/shbr-01-package-docker:latest
          name: shbr-echo
          env:
            - name: PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RESTART
              value: "2"
      restartPolicy: Always
