apiVersion: v1
kind: Service
metadata:
  name: shbr-echo
  labels:
    app: shbr-echo
spec:
  type: NodePort
  ports:
  - port: 10000
    nodePort: 32000
    protocol: TCP
  selector:
    app: shbr-echo